name: Terraform Apply

on:
  push:
    branches: 
      - main
  pull_request:

permissions:
 contents: read

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check commit message for destroy keyword
        id: check_message
        run: |
            if [[ "${{ github.event.head_commit.message }}" == *"[destroy]"* ]]; then
              echo "destroy=true" >> $GITHUB_ENV
            else
              echo "destroy=false" >> $GITHUB_ENV
            fi

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: eu-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        if: env.destroy == 'false'
        with:
          terraform_wrapper: false
      - name: Set environment variables
        run: |
          echo "AWS_PROFILE=${{ secrets.AWS_PROFILE }}" >> $GITHUB_ENV
        if: env.destroy == 'false'

      - name: Terraform Apply
        id: apply
        run:  |
          cd tf-example/
          RETRIES=5
          for i in $(seq 1 $RETRIES); do
            terraform init -backend-config="profile=${{ secrets.AWS_PROFILE }}"
          done
          terraform validate
          terraform plan
          terraform apply -auto-approve
        if: env.destroy == 'false'


